name: go HW_2
on:
  workflow_dispatch:
    inputs:
      go_version:
        description: 'Set go version'
        required: true
        default: '1.18'
        type: choice
        options:
        - 1.18
        - 1.19.1
        - 1.19.2


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go_version}}

      - name: Run main.go
        run: go run main.go